"""cambiando estado reporte

Revision ID: 727565e30503
Revises: 
Create Date: 2026-09-06 12:48:55.482297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '727565e30503'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_competencia', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('BORRADOR', 'PENDIENTE', 'APROBADO', 'RECHAZADO'),
               type_=sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADO', name='estadoreporte'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_competencia', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADO', name='estadoreporte'),
               type_=mysql.ENUM('BORRADOR', 'PENDIENTE', 'APROBADO', 'RECHAZADO'),
               existing_nullable=False)

    # ### end Alembic commands ###
